

all: lab7z1 lab7z2 lab8z1


lab7z1: lab7z1.cpp
	g++ -o lab7z1.exe lab7z1.cpp -lglm -lglut -lOpenGL -lGLU

lab7z2: lab7z2.cpp
	g++ -o lab7z2.exe lab7z2.cpp -lglm -lglut -lOpenGL -lGLU

lab8z1: lab8z1.cpp
	g++ -o lab8z1.exe lab8z1.cpp -lglm -lglut -lOpenGL -lGLU

clean: 
	rm *.exe