

all : lab6z1 lab5z1


lab6z1: lab6z1.cpp
	g++ -o lab6z1.exe -Wall lab6z1.cpp -lglm -lglut -lOpenGL -lGLU

lab5z1: lab5z1.cpp
	g++ -o lab5z1.exe -Wall lab5z1.cpp -lglm -lglut -lOpenGL -lGLU

clean: 
	rm *.exe